### ISSUE TITLE
Cannot change volume slider to a desired value with mouse [gtk2]

### ISSUE THREAD

**Issue by milos3** [nicklan/pnmixer#72] opened 2015-05-01 21:25 UTC
At the moment in gtk2 popup window I cannot just click on a selected value and expect the slider to change to that value but instead it increases/decreases by 10% (continuously if I hold).

![image](https://cloud.githubusercontent.com/assets/5746405/7244300/b7840a30-e7d9-11e4-8610-c65e8a6f7128.gif)

I did found out that on Manjaro 0.8.11 Openbox edition doesn't have this problem.

![image](https://cloud.githubusercontent.com/assets/5746405/7244304/ce82b060-e7d9-11e4-8aa7-42c2c753db6d.gif)

I looked at PKGBUILD for their pnmixer and they are using an unmodified version 0.5.1 from https://github.com/downloads/nicklan/pnmixer/pnmixer-0.5.1.tar.gz using gtk2. However I did discovered that it's because of their Menda theme. When I changed to another theme then the slider wasn't "fixed" anymore, just like in 1st gif. 

![3](https://cloud.githubusercontent.com/assets/5746405/7437588/f4ba4bc6-f058-11e4-92af-23c17a432c10.gif)

I'm not sure what they did with their Menda theme to make it better, which can be found at https://github.com/manjaro/artwork-menda.

**Comment by elboulangero** [comment] 2015-05-01 22:17
I did a little bit of digging in the net, and it happens that this is the intended behavior. Have a look at this page: http://www.gtk.org/tutorial1.2/gtk_tut-8.html#ss8.4

> Clicking button-1 in the trough will cause its adjustment's page_increment to be added or subtracted from its value, and the slider to be moved accordingly. Clicking mouse button-2 in the trough will jump the slider to the point at which the button was clicked

Button two is the middle-click. I checked, and the slider behaves as mentioned in the doc.

What you said about the Menda theme suggests that this behavior can be modified through a theme. But it's definitely not a PNMixer bug.

**Comment by hasufell** [comment] 2015-05-01 22:18
It is certainly achievable with extra code though.

**Comment by elboulangero** [comment] 2015-05-01 22:49
In my opinion, we shouldn't touch that. If every Gtk2 scales behaves the same way, except the one in PNMixer because we hacked it, well, it's weird, isn't it ? What about consistency ?
And I don't think it's worth it. I mean, once you learned that you can click the slider with button 2, everything is fine right ? You just learned how to click on a slider in the Gtk2 world, that's fine, it's never too late :)

**Comment by milos3** [comment] 2015-05-02 01:29
Oh, I did not realise that middle mouse click does just that, well now that changes things! Only thing this leaves is different behaviour between gtk2 and gtk3.

**Comment by hasufell** [comment] 2015-05-02 09:55
> different behaviour between gtk2 and gtk3

Ofc, but that's gtk...

**Comment by elboulangero** [comment] 2015-05-04 12:27
Should we close this ticket ?

**Closed** 2015-07-05 10:19 UTC
Labels: gtk2, gtk3, invalid
