### ISSUE TITLE
pnmixer overlaps icon in xfce panel

### ISSUE THREAD

**Issue by giorgosioak** [nicklan/pnmixer#180] opened 2018-06-08 22:55 UTC
Hello, pnmixer (in system tray) overlaps icon as showed in gif.

![imgur gif](https://i.imgur.com/klNADbu.gif)

**Comment by hasufell** [comment] 2018-06-09 14:56
duplicate of https://github.com/nicklan/pnmixer/issues/71

**Closed by hasufell** 2018-06-09 14:56 UTC
Labels: cantfix/wontfix
